# --- Configuración de Base de Datos (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Forzamos a Hibernate a no intentar usar un URL inexistente
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# --- Configuración de Seguridad y Producción ---
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true

# Logs desactivados de SQL en consola para evitar exposición de datos y mejorar rendimiento
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Optimización de plantillas Thymeleaf
spring.thymeleaf.cache=true